# Generated by Django 6.0.6 on 2026-06-30 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(editable=False, help_text='Auto-generated Employee ID (e.g., EMP001)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full name of the employee', max_length=200)),
                ('designation', models.CharField(help_text='Job title/designation', max_length=100)),
                ('department', models.CharField(help_text='Department name', max_length=100)),
                ('date_of_joining', models.DateField(help_text='Date of joining the company')),
                ('monthly_salary', models.DecimalField(decimal_places=2, help_text='Monthly salary in INR', max_digits=12)),
                ('bank_account', models.CharField(blank=True, help_text='Bank account number', max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
    ]
