# Generated by Django 6.0.6 on 2026-06-30 10:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_month', models.CharField(help_text='e.g., June 2026', max_length=20)),
                ('month_year', models.DateField(help_text='First day of the salary month (for filtering)')),
                ('monthly_salary', models.DecimalField(decimal_places=2, help_text='Monthly salary snapshot at time of entry', max_digits=12)),
                ('total_working_days', models.IntegerField(default=30, help_text='Total working days in the month', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('present_days', models.IntegerField(help_text='Number of days present', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('absent_days', models.IntegerField(default=0, editable=False)),
                ('salary_earned', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total deduction amount', max_digits=12)),
                ('deduction_remarks', models.TextField(blank=True, default='', help_text='Reason for deduction (e.g., Late attendance, Loan EMI)')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid in first payment', max_digits=12)),
                ('payment_date', models.DateField(blank=True, help_text='Date of first payment', null=True)),
                ('balance_salary', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('balance_paid', models.DecimalField(decimal_places=2, default=0, help_text='Balance amount paid later', max_digits=12)),
                ('balance_paid_date', models.DateField(blank=True, help_text='Date when balance was paid', null=True)),
                ('total_salary_paid', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid')], default='PENDING', editable=False, max_length=20)),
                ('is_completed', models.BooleanField(default=False, help_text='Lock record when checked — only Super Admin can unlock')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_salaries', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salary_records', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='employees.employee')),
            ],
            options={
                'ordering': ['-month_year', 'employee__employee_id'],
                'unique_together': {('employee', 'month_year')},
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('payment_type', models.CharField(choices=[('INITIAL', 'Initial Payment'), ('BALANCE', 'Balance Payment')], max_length=10)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
                ('salary_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='salary.salaryrecord')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
